#pragma once
 
#define BOOTMAGIC_LITE_ROW 0
#define BOOTMAGIC_LITE_COLUMN 0
#define DYNAMIC_KEYMAP_LAYER_COUNT 6
#define AUDIO_PIN C6
#define AUDIO_INIT_DELAY
#define STARTUP_SONG SONG(MARIO_MUSHROOM)
#define AUDIO_CLICKY